### ISSUE TITLE
Red Hat Developer Hub does not support empty owner and system labels

### ISSUE THREAD

**Issue by hguerrero** [microcks/microcks-backstage-provider#14]
### Describe the bug

When trying to deploy the backstage plugin, if there are no labels in the service, the plugin tries to put an empty label. This is not supported, hence the service is not added to the catalog.

### Expected behavior

Microcks adds a default owner and system labels.

### Actual behavior

No service is imported

### How to Reproduce?

. Install plugin
. Load service
. Wait for plugin task

### Microcks version or git rev

1.8,1

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

backstage plugin + uber jar

**Comment by lbroudoux** [comment]
I don't think this is Red Hat Developer Hub specific. If no `systemLabel` or `ownerLabel` is found on the fetched API, upstream Backstage also refuses to create a new `ApiEntity`.

**Comment by lbroudoux** [comment]
Do you mean, we should add some new specific configuration params to add default values for them?

**Comment by lbroudoux** [comment]
The connector will provide default values to `microcks` and `microcks` for both labels. This has been introduced by PR #17 by @hguerrero. Thanks mate!
