### ISSUE TITLE
Plugin does not work for backstage 1.33

### ISSUE THREAD

**Issue by javiermartingonzalez** [microcks/microcks-backstage-provider#63]
### Describe the bug

Hello, Backstage not starting after installing 1.33 version due to plugin-catalog-backend incompatibility. It seems it was not applying the migration and the backend is not starting.

With your last update, you are using @backstage/plugin-catalog-backend@1.27 version and newer version is @backstage/plugin-catalog-backend@1.28

Can you check? Uninstalling Microcks plugin solves the problem

### Actual behavior

2024-11-21T15:35:13.404Z backstage info Plugin initialization in progress, still initializing: 'app' type=initialization
C:\Repositorios\idp\backstage\node_modules\@backstage\backend-defaults\node_modules\@backstage\backend-app-api\src\wiring\BackendInitializer.ts:334
              throw new ForwardedError(
                    ^

ForwardedError [TypeError]: Plugin 'catalog' startup failed; caused by TypeError: backendOpenapiUtils.createValidatedOpenApiRouterFromGeneratedEndpointMap is not a function
    at <anonymous>

**Comment by lbroudoux** [comment]
Oh... I just tested with backstage 1.32 and was hoping to have some time before another API change... Will have a look at it.

**Comment by lbroudoux** [comment]
Hi @javiermartingonzalez,

I tried reproducing this by directly creating a new backstage 1.33 application and adding the `0.0.6` version of our plugin to it, but I didn't succeed. The plugin is installed correctly and works as expected without errors in the log.

My app `packages/backend/package.json` actually references `@backstage/plugin-catalog-backend": "^1.28.0"` as you noticed but this doesn't raise issue with `@backstage/plugin-catalog-backend": "^1.27.0` used in the Microcks plugin. 

Can you explain the process you followed to get this exception?
