### ISSUE TITLE
Config Loader issue on Backstage v1.17

### ISSUE THREAD

**Issue by fmenesesg** [microcks/microcks-backstage-provider#7]
### Describe the bug

Microcks config schema is considered invalid on Backstage version 1.17

### Expected behavior

Be able to use microcks plugin with backstage v1.17 version

### Actual behavior

Microck plugin start with error, because of [Config Loader CHANGELOG](https://github.com/backstage/backstage/blob/master/docs/releases/v1.17.0-changelog.md#backstageconfig-loader140)

### How to Reproduce?

Create and backstage 1.17 instance or upgrade an existing one
Configure the Microcks plugin as the Readme file says
Start the backstage instance
See error

### Microcks version or git rev

1.7.1

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

podman-compose

**Comment by lbroudoux** [comment]
Hi @fmenesesg,

Thanks a lot for raising this issue and associated PR! I didn't try with the latest version of Backstage and didn't notice the regression. I succeeded in reproducing it and now will have a look at your PR. Thanks!

**Comment by lbroudoux** [comment]
All good! Thanks!
